import { chromium } from "playwright";
import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import { resolve } from "node:path";
import { ARENAS } from "../src/data/arenas.js";
import { BattleSimulation } from "../src/core/battle-simulation.js";
import { calculateBuild } from "../src/core/assembly-calculator.js";
import { DEFAULT_BUILD } from "../src/data/parts.js";
import { normalizeLabState } from "../src/core/lab-state.js";

let checks=0;
const check=(value,label)=>{assert.ok(value,label);checks++;};
const build=calculateBuild(DEFAULT_BUILD);
const battle=()=>new BattleSimulation({playerBuild:build,enemyBuild:build,arena:ARENAS.ruins});
const sim=battle();
sim.launch({power:.86,height:.45,direction:0,angle:0});
sim.player.position={x:6,y:6};
sim.player.velocity={x:0,y:0};
sim.step(1/60,{x:0,y:0},{x:0,y:0});
check(sim.phase==="running","Square corners are playable, not circular ring-outs");
sim.player.position={x:ARENAS.ruins.wallRadius+.02,y:0};
sim.player.velocity={x:3,y:0};
sim.step(1/60,{x:0,y:0},{x:0,y:0});
check(sim.player.velocity.x<0,"Square balustrade rebounds outward movement");
sim.player.position={x:2.9,y:3.30};
sim.player.velocity={x:0,y:-5};
sim.step(1/60,{x:0,y:0},{x:0,y:0});
check(sim.player.velocity.y>0 && sim.events.some(e=>e.type==="obstacle"),"Visible blocker produces rebound and contact event");
sim.player.position={x:2.9,y:2.2};
sim.player.velocity={x:0,y:0};
sim.step(1/60,{x:0,y:0},{x:0,y:0});
check(Math.abs(sim.player.position.y-2.2)>=1.09,"Interior overlap resolves outside solid obstacle");
sim.player.position={x:6.7,y:2.4};
sim.player.velocity={x:0,y:0};
sim.step(1/60,{x:0,y:0},{x:0,y:0});
check(Math.hypot(sim.player.position.x-6.7,sim.player.position.y-2.4)>1,"Perimeter column footing is solid");
sim.player.position={x:8.3,y:0};
sim.step(1/60,{x:0,y:0},{x:0,y:0});
check(sim.result?.reason==="ring_out","Square edge crossing ends the round");
const a=battle(),b=battle();
for (const s of [a,b]) s.launch({power:.86,height:.45,direction:.3,angle:0});
for(let i=0;i<600;i++){a.step(1/60,{x:1,y:-.4});b.step(1/60,{x:1,y:-.4});}
check(JSON.stringify(a.player)===JSON.stringify(b.player),"New map simulation remains deterministic");
check(normalizeLabState({settings:{room:"advanced"}}).settings.room==="childhood","Starter save cannot equip advanced room");
check(normalizeLabState({xp:120,settings:{room:"advanced"}}).settings.room==="advanced","Earned LV2 restores advanced room");

const out=resolve("../.impeccable/review/worlds");
await mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH??"C:/Program Files/Google/Chrome/Application/chrome.exe",headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
const key="spin-core-web-prototype-v2";
await context.addInitScript(key=>{
  if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify({version:2,tutorial:{completed:true,stage:"complete"},lab:{xp:120}}));
},key);
const page=await context.newPage();
const errors=[];
page.on("pageerror",e=>errors.push(e.message));
const base=process.env.LAB_TEST_URL??"http://127.0.0.1:5173";
const screenshot=async(name)=>{
  await page.waitForTimeout(1000);
  await page.screenshot({path:`${out}/${name}.png`});
  await page.locator(".game-shell").screenshot({path:`${out}/${name}-portrait.png`});
};
try {
  await page.goto(`${base}/#collection`);
  await page.waitForFunction(()=>!document.querySelector("[data-show-loadout]")?.disabled);
  await page.locator('[data-collection="inspect"]').click();
  check(await page.locator(".collection-view").getAttribute("data-inspect")==="true","Inspection opens in the same showroom");
  await page.locator('[data-inspect-part="attackRing"]').click();
  check(await page.locator('[data-inspect-part="attackRing"]').getAttribute("aria-pressed")==="true","Inspection selects canonical part");
  await screenshot("inspection-desktop");
  const canvas=page.locator(".collection-scene canvas");
  const box=await canvas.boundingBox();
  await page.mouse.move(box.x+box.width*.5,box.y+box.height*.35);
  await page.mouse.down();
  await page.mouse.move(box.x+box.width*.65,box.y+box.height*.4,{steps:12});
  await page.mouse.up();
  await page.mouse.wheel(0,-100);
  check(await page.locator(".collection-view").getAttribute("data-inspect")==="true","Orbit and zoom preserve inspection state");
  await page.locator('[data-collection="inspect-back"]').click();
  await page.waitForTimeout(1000);
  await canvas.click({position:{x:box.width*.5,y:box.height*.36}});
  check(await page.locator(".collection-view").getAttribute("data-inspect")==="true","Clicking the actual top opens inspection");
  await page.setViewportSize({width:390,height:844});
  await screenshot("inspection-mobile");
  await page.locator('[data-collection="inspect-back"]').click();
  await page.setViewportSize({width:1440,height:1000});
  await page.locator('[data-collection="lab"]').click();
  await page.waitForFunction(()=>!document.querySelector(".lab-start")?.disabled);
  check(await page.locator('.lab-view[data-room="childhood"]').count()===1,"Childhood desk is default");
  await screenshot("childhood-desktop");
  await page.setViewportSize({width:390,height:844});
  await screenshot("childhood-mobile");
  await page.setViewportSize({width:1440,height:1000});
  await page.locator('[data-lab="settings"]').click();
  await page.locator('[data-setting="room"]').selectOption("advanced");
  await page.keyboard.press("Escape");
  check(await page.locator('.lab-view[data-room="advanced"]').count()===1,"Advanced lab remains selectable at LV2");
  await page.locator('[data-lab="battle"]').click();
  check(await page.locator(".arena-card").count()===5,"All five arenas are available");
  for(const arena of ["metal","street","ruins"]){
    await page.locator(`.arena-card[data-arena="${arena}"]`).click();
    await page.waitForFunction(id=>document.querySelector(".game-shell")?.dataset.arena===id,arena);
    await page.waitForFunction(()=>document.querySelector("#three-stage")?.dataset.assetState==="ready");
    await page.waitForTimeout(600);
    check(await page.locator(".game-shell").getAttribute("data-arena")===arena,`${arena} selection survives carousel settling`);
    await page.locator("#start-battle").click();
    await page.waitForFunction(()=>!document.querySelector("#launch-button")?.disabled);
    check(await page.locator(".game-shell").getAttribute("data-arena")===arena,`${arena} is the actual battle map`);
    await screenshot(`${arena}-desktop`);
    await page.locator("#launch-button").click();
    await page.waitForFunction(()=>document.querySelector("#launch-controls")?.classList.contains("is-hidden"));
    check(true,`${arena} launches without asset errors`);
    await page.waitForTimeout(1800);
    await screenshot(`${arena}-running`);
    await page.setViewportSize({width:390,height:844});
    await screenshot(`${arena}-mobile`);
    check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${arena} has no mobile horizontal overflow`);
    await page.setViewportSize({width:1440,height:1000});
    await page.goto(`${base}/#map`);
    await page.reload();
  }
  check(errors.length===0,`No page exceptions: ${errors.join("; ")}`);
  await page.route("**/street.glb*",route=>route.abort());
  await page.locator('.arena-card[data-arena="street"]').click();
  await page.waitForFunction(()=>document.querySelector("#three-stage")?.dataset.assetState==="error");
  await page.locator("#start-battle").click();
  await page.waitForFunction(()=>document.querySelector("#three-stage")?.dataset.assetState==="error");
  check(await page.locator("#launch-button").isDisabled(),"Missing asset explicitly blocks launch");
  check(await page.locator(".arena-asset-status").isVisible(),"Missing asset presents recovery message");
  console.log(`PASS: ${checks} world, inspection and collision checks; ${out}`);
} finally {await browser.close();}
