import assert from "node:assert/strict";
import { mkdir, writeFile } from "node:fs/promises";
import { chromium } from "playwright";
import { normalizeBattleNotes, compareBuilds, trainingCue } from "../src/core/growth-state.js";
import { DEFAULT_BUILD, getPart } from "../src/data/parts.js";
import { CHAPTER_MOMENTS, unlockedChapterMoments } from "../src/data/chapter-moments.js";
import { normalizeCampaign, settleMission } from "../src/core/campaign-state.js";
import { CAMPAIGN_MISSIONS } from "../src/data/campaign.js";

let checks = 0;
const check = (value, name) => { assert.ok(value, name); checks++; };
const baseline = { build: DEFAULT_BUILD, customizations: {}, time: 12, winner: "enemy" };
check(Object.keys(normalizeBattleNotes(null)).length === 0, "Legacy save has no invented baseline");
check(Object.keys(normalizeBattleNotes({ "loadout-1": { ...baseline, build: {} }, unexpected: baseline })).length === 0, "Invalid slots/builds are rejected");
check(Object.keys(normalizeBattleNotes({ "loadout-1": { ...baseline, customizations: { [DEFAULT_BUILD.tip]: null } } })).length === 1, "Null customization migrates safely");
const normalized = normalizeBattleNotes({ "loadout-1": baseline });
check(JSON.stringify(normalizeBattleNotes(normalized)) === JSON.stringify(normalized), "Snapshot migration is idempotent");
check(compareBuilds(baseline, baseline).changes.length === 0, "Same configuration is not growth");
const changed = { build: { ...DEFAULT_BUILD, driverShaft: "driver_shaft.low_stable" }, customizations: {} };
check(compareBuilds(baseline, changed).changes.length === 1, "Canonical replacement reports one changed part");
check(compareBuilds(baseline, { ...baseline, customizations: { [DEFAULT_BUILD.tip]: { size: 1.2 } } }).changes[0].includes("DIY"), "Same part DIY also reports change");
check(trainingCue({ phase: "running", steered: false, spinHarvested: 0 }).id === "steer", "No fabricated steering completion");
check(trainingCue({ phase: "running", steered: true, spinHarvested: 0, zone: { cooling: true } }).copy.includes("冷却"), "Cooling is not called active supply");
check(trainingCue({ phase: "running", steered: true, spinHarvested: .01 }).id === "supplied", "Actual harvested spin confirms learning");
let campaign = normalizeCampaign();
for (const mission of CAMPAIGN_MISSIONS) {
  const prior = unlockedChapterMoments(campaign).length;
  const input = { missionId: mission.id, battleId: `growth-${mission.id}`,
    result: { winner: "player", reason: "spin_out", time: 20 }, durabilityRatio: 1, loadout: { name: "主力", build: DEFAULT_BUILD } };
  const result = settleMission(campaign, input);
  const isBoundary = CHAPTER_MOMENTS.some(m => m.missionId === mission.id);
  check(result.firstClear && unlockedChapterMoments(result.campaign).length === prior + Number(isBoundary), `${mission.id}: only chapter completion unlocks response`);
  campaign = result.campaign;
  check(!settleMission(campaign, { ...input, battleId: `replay-${mission.id}` }).firstClear, `${mission.id}: replay is not first clear`);
}
check(unlockedChapterMoments(normalizeCampaign({ completed: ["our-names"] })).length === 0, "Malformed completion cannot reveal final response");

const out = "../.impeccable/review/growth";
await mkdir(out, { recursive: true });
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH ?? "C:/Program Files/Google/Chrome/Application/chrome.exe", headless: true });
const base = process.env.LAB_TEST_URL ?? "http://127.0.0.1:5173";
const key = "spin-core-web-prototype-v2";
const context = await browser.newContext({ viewport: { width: 390, height: 844 }, reducedMotion: "reduce" });
const page = await context.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
const saved = () => page.evaluate(key => JSON.parse(localStorage.getItem(key)), key);
const capture = async name => {
  if (process.env.GROWTH_CAPTURE === "0") return;
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  await page.screenshot({ path: `${out}/${name}.png`, fullPage: true });
};
const pair = async name => {
  await page.setViewportSize({ width: 390, height: 844 }); await capture(`${name}-mobile`);
  await page.setViewportSize({ width: 1440, height: 1000 }); await capture(`${name}-desktop`);
  await page.setViewportSize({ width: 390, height: 844 });
};
try {
  await page.goto(base);
  await page.waitForFunction(() => document.querySelector("#launch-button")?.disabled === false);
  check((await page.locator("#tutorial-title").textContent()).includes("转起来"), "Fresh launch has a single simple goal");
  await pair("launch");
  await page.locator("#pause-battle").click();
  await page.locator("#tutorial-action").click();
  check(new URL(page.url()).hash === "#battle", "Ready return can resume actual training");
  await page.waitForFunction(() => document.querySelector("#launch-button")?.disabled === false);
  await page.locator("#launch-button").click();
  check((await page.locator("#tutorial-title").textContent()).includes("轻推"), "Launching advances to control guidance");
  await page.keyboard.down("a");
  await page.waitForFunction(() => document.querySelector("#tutorial-title").textContent.includes("已完成轻推"));
  await page.keyboard.up("a");
  await pair("steer");
  await page.locator("#result-card:not(.is-hidden)").waitFor({ timeout: 100000 });
  check((await saved()).coins === 180, "First battle retains 180 reward");
  check(Boolean((await saved()).battleNotes["loadout-1"]), "Completed battle creates real slot baseline");
  check(await page.locator("#tutorial-card").isHidden(), "Teaching never covers result");
  await page.locator("#result-assembly").click();
  await page.reload();
  check(Boolean((await saved()).battleNotes["loadout-1"]), "Baseline survives refresh before buying");
  await page.locator("#tutorial-action").click();
  const partId = "driver_shaft.low_stable";
  await page.locator(`[data-part-id="${partId}"]`).click();
  await page.locator("#purchase-cancel").click();
  check((await saved()).coins === 180, "Cancelling purchase keeps bounty");
  await page.locator(`[data-part-id="${partId}"]`).click();
  await page.locator("#purchase-confirm").click();
  check((await saved()).coins === 180 - getPart(partId).price, "First part uses canonical price");
  check((await saved()).tutorial.stage === "second_battle", "Purchase opens existing second training stage");
  await page.locator("#assembly-comparison > summary").click();
  check((await page.locator("#assembly-comparison").textContent()).includes("驱动中轴"), "Assembly identifies changed part");
  check(await page.locator("#assembly-comparison tbody tr").count() === 5, "Comparison contains five real ratings");
  await pair("comparison");
  await page.reload();
  check((await page.locator("#tutorial-copy").textContent()).includes("理论评分"), "Second training retains explanatory context after refresh");
  const firstSnapshot = (await saved()).battleNotes["loadout-1"];
  await page.locator("#tutorial-action").click();
  await page.waitForFunction(() => document.querySelector("#launch-button")?.disabled === false);
  await page.locator("#launch-button").click();
  await page.locator("#pause-battle").click();
  await page.locator("#pause-exit").click();
  check(JSON.stringify((await saved()).battleNotes["loadout-1"]) === JSON.stringify(firstSnapshot), "Abandon does not overwrite completed baseline");
  await page.locator("#tutorial-action").click();
  await page.waitForFunction(() => document.querySelector("#launch-button")?.disabled === false);
  await page.locator("#launch-button").click();
  console.log("Migration, chapter boundaries, first battle, purchase, comparison and abandonment passed; completing second training.");
  await page.locator("#result-card:not(.is-hidden)").waitFor({ timeout: 100000 });
  check((await saved()).tutorial.completed, "Second actual battle completes original tutorial");
  check((await saved()).battleNotes["loadout-1"].build.driverShaft === partId, "Finished second battle records its actual loadout");
  await page.locator("#result-details > summary").click();
  await page.locator("#result-details .comparison-disclosure > summary").click();
  check((await page.locator("#result-comparison").textContent()).includes("驱动中轴"), "Result compares against prior snapshot, not overwritten one");
  await pair("result-comparison");
  await page.locator("#result-restart").click();
  check(new URL(page.url()).hash === "#journey", "Graduation leads into the story");
  await page.locator(".journey-moments > summary").click();
  check(await page.locator(".journey-moments article").count() === 0, "Future chapter dialogue stays hidden");
  await page.locator('.journey-prep [data-go="assembly"]').click();
  await page.locator("#next-loadout").click();
  check(await page.locator("#assembly-comparison > div").textContent().then(t => t.includes("还没有")), "Different loadout never borrows another baseline");

  // A migrated completed chapter fixture tests recall without fabricating a live victory.
  await page.evaluate(({ key, firstTwo }) => {
    const state = JSON.parse(localStorage.getItem(key));
    state.campaign = { completed: firstTwo, mastered: [], journal: [] };
    localStorage.setItem(key, JSON.stringify(state));
  }, { key, firstTwo: CAMPAIGN_MISSIONS.slice(0, 2).map(m => m.id) });
  await page.goto(`${base}/#journey`);
  await page.reload();
  await page.locator(".journey-moments > summary").click();
  check(await page.locator(".journey-moments article").count() === 1, "Migrated chapter gets exactly its unlocked reply");
  check((await page.locator(".journey-moments").textContent()).includes("阿砾"), "Reply names the actual companion");
  await page.locator(".journey-moments").scrollIntoViewIfNeeded();
  await pair("chapter");
  await page.reload();
  check(await page.locator(".journey-moments article").count() === 1, "Reply remains available on reload without extra reward");
  check(errors.length === 0, `No runtime exceptions: ${errors.join("; ")}`);
  const skip = await browser.newContext();
  const skipPage = await skip.newPage();
  await skipPage.goto(base);
  await skipPage.locator("#tutorial-skip").click();
  check(await skipPage.locator("#tutorial-card").isHidden(), "Experienced player can skip teaching");
  await skipPage.reload();
  check(await skipPage.locator("#tutorial-card").isHidden(), "Skip persists");
  await skip.close();
  await writeFile(`${out}/verification.json`, JSON.stringify({ checks, status: "PASS", errors }, null, 2));
  console.log(`PASS ${checks}: growth, training and chapter checks`);
} finally { await browser.close(); }
